name: Deploy Purnukka Stack to Polar55

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: master.purnukka.com/wp-content/
        local-dir: ./
        protocol: ftp
        port: 21
        # Tarkennettus exclude-lista ilman ylimääräisiä tähtiä, jotka voivat sekoittaa polkuja
        exclude: |
          .git/**
          .github/**
          .vscode/**
          .gitignore
          README.md
          sftp.json
          templates/**
          **/node_modules/**